# Generated by Django 5.2.12 on 2026-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
