# Generated by Django 5.2.12 on 2026-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_carro_marca_alter_carro_modelo_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
