# Generated by Django 5.2.12 on 2026-03-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('dia_inteiro', 'Dia Inteiro')], max_length=20)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.carro')),
            ],
        ),
    ]
