# Generated by Django 5.2.12 on 2026-03-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_carro_placa_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='carro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agenda.carro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('dia_inteiro', 'Dia Inteiro')], default='', max_length=20),
        ),
    ]
