# Generated by Django 5.2.12 on 2026-03-25 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_reserva_aprovada_alter_reserva_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
