# Generated by Django 5.2.12 on 2026-03-25 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_reserva_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataEntrega',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
