# Generated by Django 5.2.12 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_reserva_data_reserva_dataentrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataEntrega',
            field=models.DateField(),
        ),
    ]
