# Generated by Django 5.2.12 on 2026-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_reserva_dataentrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='carro',
        ),
    ]
