# Generated by Django 5.2.12 on 2026-03-26 17:31

import agenda.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_remove_reserva_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataEntrega',
            field=models.DateField(validators=[agenda.models.validar_data_futura]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateField(default=datetime.datetime.now, validators=[agenda.models.validar_data_futura]),
        ),
    ]
