# Generated by Django 5.2.12 on 2026-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_reserva_dataentrega_alter_reserva_datasaida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horarioSolicitacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
