# Generated by Django 5.2.12 on 2026-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_reserva_horariosolicitacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='carro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='carro',
            name='tipo',
            field=models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro'), ('caminhonete', 'Caminhonete')], default=''),
        ),
    ]
