# Generated by Django 5.2.12 on 2026-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_delete_contact_carro_ativo_carro_foto_carro_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhonete', 'Caminhonete')], default='')),
                ('observacao', models.TextField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculos/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
