# Generated by Django 5.2.12 on 2026-03-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_veiculo_delete_carro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='ativo',
            new_name='status',
        ),
    ]
