# Generated by Django 5.2.12 on 2026-03-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_rename_ativo_veiculo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='observacao',
        ),
    ]
