# Generated by Django 5.2.12 on 2026-03-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_veiculo_marca_alter_veiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.veiculo', verbose_name='Veículo'),
        ),
    ]
