# Generated by Django 5.2.12 on 2026-03-27 19:07

import agenda.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_reserva_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dataEntrega',
            field=models.DateTimeField(validators=[agenda.models.validar_data_futura]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dataSaida',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[agenda.models.validar_data_futura]),
        ),
    ]
