# Generated by Django 5.2.12 on 2026-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_alter_reserva_dataentrega_alter_reserva_datasaida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='periodo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='destino',
            field=models.CharField(default='', max_length=100),
        ),
    ]
